export const REGISTER_NEW_SURVEY = 'REGISTER_NEW_SURVEY';
export const ADD_NEW_QUESTION = 'ADD_NEW_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';